marketplaces/urls.py
from django.conf import settings
from django.conf.urls.defaults import *
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    (r'^', include('market.urls')),
    (r'^buy/', include('market_buy.urls')),
    (r'^sell/', include('market_sell.urls')),
    (r'^community/', include('market_community.urls')),
    (r'^admin/reports/', include('reports.urls')),
    
    url(r'^admin/', include(admin.site.urls), name="admin"),
    url(r'^logout/$', 'auth.views.logout', name='logout'),
    url(r'^map/([\d]+)/$', 'bidding.views.bidding_map', name='bidding_map'),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
    )

marketplaces/apps/market/models.py
from auth.models import User

from django.contrib import admin
from django.db import models
from django.template.defaultfilters import slugify

class MarketPlace(models.Model):
    #length  
    name = models.CharField(max_length=92)
    slug = models.SlugField(max_length=92, unique=True)
    title = models.CharField(max_length=92)
    base_domain =  models.CharField(max_length=128, help_text="example: greatcoins.com", unique=True)
    contact_email = models.EmailField(help_text="This email will be shown in the contact us page", default="contact@yourstore.com")
    contact_phone = models.CharField(max_length=128, help_text="This phone will be shown in the contact us page", default="")
    charge_on_card_as = models.CharField(max_length=255, help_text="Collector City LLC", default="")
    template_prefix = models.SlugField(max_length=92, help_text="example: greatcoins", unique=True)
    
    def __unicode__(self):
        return self.name
    
    def privacy_policy(self):
        policies = self.privacypolicy_set.all()
        l = policies.count()
        if l > 0: return policies[l-1].text
   
class MarketCategory(models.Model):
    marketplace = models.ForeignKey(MarketPlace)
    name = models.CharField(max_length=60)
    slug = models.SlugField(max_length=60, unique=True)
    order = models.IntegerField(default=255)
    
    class Meta:
        ordering = ['order']

    def __unicode__(self):
        return "%s > %s" % (self.marketplace, self.name)
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(MarketCategory, self).save(*args, **kwargs)

class MarketSubCategory(models.Model):
    marketplace = models.ForeignKey(MarketPlace)
    name = models.CharField(max_length=60)
    slug = models.SlugField(max_length=60)
    parent = models.ForeignKey(MarketCategory, null=True, blank=True, related_name='subcategories')
    order = models.IntegerField(default=255)
    
    class Meta:
        unique_together = (('parent', 'slug'),)
        ordering = ['order']
    
    def __unicode__(self):
        return "%s > %s" % (self.parent, self.name)
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(MarketSubCategory, self).save(*args, **kwargs)

class MarketMailingListMember(models.Model):
    marketplace = models.ForeignKey(MarketPlace)
    email = models.EmailField()
    def __str__(self):
        return "%s > %s" % (self.marketplace, self.email)
    
class MarketPostCategory(models.Model):
    tag = models.CharField(max_length=80)
    slug = models.SlugField(max_length=80, unique=True)
    def __unicode__(self):
        return self.tag
        
    def save(self, *args, **kwargs):
        self.slug = slugify(self.tag)
        super(MarketPostCategory, self).save(*args, **kwargs)

class MarketBlogPost(models.Model):
    marketplace = models.ForeignKey(MarketPlace)
    title = models.CharField(max_length=60)
    body = models.TextField()
    posted_on = models.DateTimeField(auto_now_add=True)
    posted_by = models.ForeignKey(User)
    views = models.IntegerField(default=0, editable=False)
    allow_comments = models.BooleanField(default=False)
    slug = models.SlugField(max_length=80, unique=True, editable=False)
    #tags = models.
    
    class Admin:
        list_display   = ('title', 'posted_by', 'posted_on')
        list_filter    = ('publisher', 'publication_date')
        ordering       = ('-posted_on',)
        search_fields  = ('title', 'posted_on')

    def comments(self):
        comment_list = MarketPostComment.objects.filter(post=self).order_by("-commented_on")
        return comment_list
        
    def tags(self):
        return []
        
    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(MarketBlogPost, self).save(*args, **kwargs)
        
    def __unicode__(self):
        return "%s > %s" % (self.marketplace, self.title)
    
    def visited(self):
        self.views = self.views + 1
        self.save()
        
    def date(self):
        return self.posted_on.strftime("%B %d, %Y")

class MarketPostPick(models.Model):
    marketplace = models.ForeignKey(MarketPlace)
    post = models.ForeignKey(MarketBlogPost)
    order = models.IntegerField(default=5)


class MarketPostComment(models.Model):
    post = models.ForeignKey(MarketBlogPost)
    comment = models.TextField()
    commented_on = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User)

    def date(self):
        return self.commented_on.strftime("%B %d, %Y")

class PrivacyPolicy(models.Model):
    marketplace = models.ForeignKey(MarketPlace)
    text = models.TextField(default="")
    
    def __unicode__(self):
        return "%s > Privacy Policy" % self.marketplace
    
class TermsAndConditions(models.Model):
    marketplace = models.ForeignKey(MarketPlace)
    text = models.TextField(default="")
    
    def __unicode__(self):
        return "%s > Terms & Conditions" % self.marketplace

marketplaces/apps/market_buy/models.py
from django.db import models
from django.conf import settings

from market.models import MarketPlace, MarketCategory, MarketSubCategory
from auth.models import User

class WishListItem(models.Model):
    marketplace = models.ForeignKey(MarketPlace)
    posted_on = models.DateTimeField(auto_now_add=True)
    posted_by = models.ForeignKey(User)
    ideal_price = models.DecimalField(max_digits=11, decimal_places=2)
    description = models.TextField()
    category = models.ForeignKey(MarketCategory)
    subcategory = models.ForeignKey(MarketSubCategory, blank=True, null=True)
    public = models.BooleanField(default=False)
    def __str__(self):
        return "%s - %s" % (self.marketplace, self.description)

class Show(models.Model):
    marketplace = models.ForeignKey(MarketPlace)
    name = models.CharField(max_length=128)
    date_from = models.DateField()
    date_to = models.DateField()
    time_from = models.TimeField()
    time_to = models.TimeField()
    address = models.CharField(max_length=128)
    city = models.CharField(max_length=128) 
    country = models.CharField(max_length=128, default="US")
    state = models.CharField(max_length=128)
    zip = models.CharField(max_length=10)
    contact_info = models.CharField(max_length=128)
    admission = models.DecimalField(max_digits=11, decimal_places=2, default="0.0")
    location = models.CharField(max_length=255, default="49.00, -96.00")
    def is_active(self):
        import datetime
        today = datetime.datetime.today()
        return today < self.date_to
    
    def duration(self):
        dif = self.date_to - self.date_from
        return dif.days
        
    def __str__(self):
        return "%s > %s (%s)" % (self.marketplace, self.name, self.city)
    
    def save(self):
        from geopy import geocoders
        super(Show, self).save()
        try:
            g = geocoders.Google(settings.GOOGLE_KEY)
            place = "%s, %s, %s, %s" % (self.address, self.city, self.state, self.country)
            place, point = g.geocode(place)
            self.location = "%s,%s" % point
            super(Show, self).save()
        except:
            pass
        
    def geo_location(self):
        return self.location.split(",")  

    def will_go_show(self, shop):
        from shops.models import DealerToShow
        try:
            DealerToShow.objects.filter(shop=shop, show=self).get()
            return True
        except DealerToShow.DoesNotExist:
            return False 
            
        
#TODO: change to EditorProductPick
class EditorPick(models.Model):
    marketplace = models.ForeignKey(MarketPlace)
    order = models.IntegerField(default=5)
    product = models.ForeignKey("inventory.Product")
    def __str__(self):
        return "%s > %s (%s)" % (self.marketplace, self.product, self.order)

class MarketPlacePick(models.Model):
    marketplace = models.ForeignKey(MarketPlace)
    order = models.IntegerField(default=5)
    product = models.ForeignKey("inventory.Product")
    def __str__(self):
        return "%s > %s (%s)" % (self.marketplace, self.product, self.order)
    
class DealerPick(models.Model):
    marketplace = models.ForeignKey(MarketPlace)
    order = models.IntegerField(default=5)
    shop = models.ForeignKey("shops.Shop")
    description = models.TextField(default="Dealer description here")
    def __str__(self):
        return "%s > %s (%s)" % (self.marketplace, self.shop, self.order)
    
class BestSeller(models.Model):
    shop = models.ForeignKey("shops.Shop")
    from_date = models.DateTimeField()
    to_date = models.DateTimeField()
    revenue = models.DecimalField(max_digits=11, decimal_places=2)
    def __str__(self):
        return "%s > %s" % (self.shop, self.revenue)

marketplaces/apps/market_buy/forms.py
# -*- coding: UTF-8 -*-
import logging
from django import forms
from auth.models import User
from django.db.models import Model
from django.db.models.query import QuerySet
from django.forms import ModelForm
from django.utils.translation import ugettext as _

from haystack.forms import SearchForm
from haystack.query import EmptySearchQuerySet

from auth.forms import UserCreationForm 
from market.models import MarketSubCategory, MarketCategory
from market_buy.models import WishListItem, Show


class WishListItemForm(ModelForm):
    
    class Meta:
        model = WishListItem
        exclude = ['marketplace', 'posted_by']
        
class ShowForm(ModelForm):
    
    class Meta:
        model = Show
        exclude = ['marketplace']
        

class BuyerForm(UserCreationForm):
    email =  forms.EmailField()


SORT_CHOICES = (
    ("price", _("Price")),
    ("-starts_at", _("Age")),
    ("relevance", _("Relevance")),
    #("dealer", _("Dealer")),
    #("auction", _("Auction")),
    #("forsale", _("For sale")),
)

INCLUDE_CHOICES = (
    ("title", _("Item Title")),
    ("description", _("Item Description")),
    ("dealer", _("Dealer Name")),
)

VIEW_BY_CHOICES = (
    ("gallery", _("Gallery")),
    ("list", _("List")),
)


class SubCategoriesField(forms.ModelMultipleChoiceField):
    """
    A ModelMultipleChoiceField that renders an empty select input
    and validates the selected item against the MarketSubCategories.
    """


    def __init__(self, *args, **kwargs):
        kwargs.update({"required": False, "widget": forms.Select(attrs={"size": 20}),
            "queryset": MarketSubCategory.objects.none()})
        super(SubCategoriesField, self).__init__(*args, **kwargs)

    def clean(self, value):
        if value:
            try:
                subcategory = MarketSubCategory.objects.get(pk=value)
            except MarketSubCategory.DoesNotExist:
                raise forms.ValidationError(_("Choosen subcategory does not exist."))
            return subcategory

        return None


class AdvancedSearchForm(SearchForm):
    
    q = forms.CharField(max_length=200, label=_("Search for"), required=False)
    sort = forms.ChoiceField(initial="price", choices=SORT_CHOICES)

    categories = forms.ChoiceField(required=False,
        choices=MarketCategory.objects.values_list("id", "name").order_by("name"), 
        widget=forms.Select(attrs={"size": 20}))
    subcategories = SubCategoriesField()

    include = forms.MultipleChoiceField(label=_("Include In Search"), 
        required=False, widget=forms.CheckboxSelectMultiple(), 
        initial=["title", "description", "dealer"], choices=INCLUDE_CHOICES)

    from_price = forms.DecimalField(label=_("Filter By Price"), required=False)
    to_price = forms.DecimalField(label=_("to"), required=False)

    view_by = forms.ChoiceField(choices=VIEW_BY_CHOICES, 
        widget=forms.RadioSelect(), initial="gallery")

    def __init__(self, marketplace, *args, **kwargs):
        super(AdvancedSearchForm, self).__init__(*args, **kwargs)
                
        self.fields.keyOrder = ["q", "categories", "subcategories", 
            "include", "from_price", "to_price", "sort", "view_by"]
        self.marketplace = marketplace
        
    def search(self):
        
        if self.is_valid():
            sqs = sqs = self.searchqueryset.models("inventory.Product")\
                .filter(marketplace_id=self.marketplace.id)

            q = self.cleaned_data.get("q")
            if q:
                sqs = sqs.auto_query(q)
            
            data = self.cleaned_data
            
            params_dict = {} 
            if self.cleaned_data["subcategories"]:
                # only one subcategory may get selected ;)
                params_dict.update({"subcategory_id": self.cleaned_data["subcategories"].id})

            # if we are going to filter by subcategory then filtering by category is
            # superfluous. so we check this first
            if not self.cleaned_data["subcategories"] and self.cleaned_data["categories"]: 
                # only one category may get selected too
                params_dict.update({"category_id": self.cleaned_data["categories"]})

            if self.cleaned_data["from_price"]:
                params_dict.update({"price__gte": self.cleaned_data["from_price"]})

            if self.cleaned_data["to_price"]:
                params_dict.update({"price__lte": self.cleaned_data["to_price"]})

            if params_dict:
                sqs = sqs.filter(**params_dict)

            # decide how to sort results
            sort_field = self.cleaned_data["sort"]
            if sort_field:
                if sort_field != "relevance":
                    sqs = sqs.order_by(sort_field)

            return sqs

        return EmptySearchQuerySet()


    def clean(self):
        super(AdvancedSearchForm, self).clean()
        
        data = self.cleaned_data
        
        if data.get("subcategories") and not data.get("categories"):
            raise forms.ValidationError(_("You must choose a category"))

        return data

    def _as_tuple_list(self):
        param_tuples = []
        
        if not self.cleaned_data:
            return []

        for field, value in self.cleaned_data.iteritems():
            if not value:
                continue
        
            if isinstance(value, (list, QuerySet)):
                for item in value:
                    if isinstance(item, Model):
                        param_tuples.append((field, item.pk))
                    else:
                        param_tuples.append((field, item))
            else:
                if isinstance(value, Model):
                    param_tuples.append((field, value.pk))
                else:
                    param_tuples.append((field, value))

        return param_tuples
                
    def get_qs(self):
        """
        Return the field names and values encoded in a querystring 
        so we may give the user a link to go back from results page
        to the original search form in order to refine his search
        """
        return "&".join(["%s=%s" % tuple for tuple in self._as_tuple_list()])

marketplaces/templates/default/buy/advanced_search.html
{% extends "default/base.html" %}
{% load i18n uni_form_tags %}

{% block content %}

<div id="breadcrumbs" class="grid_18">
    <a href="{% url market_home %}">{% trans "Home" %}</a> 
    &raquo; <a href="{% url market_buy %}">{% trans "Buy" %}</a> 
    &raquo; {% trans "Advanced Search" %}
</div>
<div class="grid_17 block_main_content margin_h" id="advanced-search">
    <h3>{% trans "Advanced Search" %}</h3>
    <form class="uniForm" method="GET" action="{% url buy_advanced_search %}">
    {% uni_form form helper %}
    </form>
</div>


<script type="text/javascript">
	$("#id_categories").click(function(){
		var selection = $(this).val();
		categories= new Array();
		categories.push(selection);
		
		$("#id_subcategories").empty();
	    
	    if (categories.length > 0){
		      $.post("{% url ajax_get_subcategories %}", { 'categories': categories }, function(data){
			      	$("#id_subcategories").append(data);
		      });
     	}      		
	});

    /* fire categories box's click event on document load event 
       so subcategories box get filled if there's a selected category
    */
    $(document).ready(function() {
       $("#id_categories").click();
    });
</script>


{% endblock %}

marketplaces/templates/default/buy/advanced_search_results.html
{% extends "default/base.html" %}
{% load i18n sell_tags %}

{% block content %}
    <div id="breadcrumbs" class="grid_18">
        <a href="{% url market_home %}">{% trans "Home" %}</a> 
        &raquo; <a href="{% url market_buy %}">{% trans "Buy" %}</a> 
        &raquo; <a href="{% url buy_advanced_search %}?{{ form.get_qs }}">
            {% trans "Advanced Search Results" %}
        </a>
    </div>

	
    <div id="view-mode-container" class="grid_17 block_main_content margin_h {{ view_mode }}">
    	{% with result_list.object_list|length as result_count %}
            <h3>{% blocktrans %}Listing {{ result_count }} results from {{ total }} items found {% endblocktrans %}</h3>
        {% endwith %}
        <p>
            <a href="{% url buy_advanced_search %}?{{ form.get_qs }}">
                {% trans "Go back and refine your search again" %}
            </a>
        </p>

        <div id="view-buttons" class="grid_17">
            <span class="view_mode">{% trans "View as" %}:</span> 
            <div class="gallery-buttons">
                <a href="#mode-list" onclick="$('#view-mode-container').toggleClass('gallery').toggleClass('list'); return false;">
                    <img src="{{ MEDIA_URL }}img/list-view.jpg" width="20" height="20" title="{% trans 'Switch to List View' %}" />
                </a>
                <img src="{{ MEDIA_URL }}img/gallery-view-sel.jpg" width="20" height="20" title="{% trans 'Gallery View' %}" />
            </div>
            <div class="list-buttons" onclick="$('#view-mode-container').toggleClass('gallery').toggleClass('list'); return false;">
                <img src="{{ MEDIA_URL }}img/list-view-sel.jpg" width="20" height="20" title="{% trans 'List View' %}" />
                <a href="#mode-gallery onclick="$('#view-mode-container').toggleClass('gallery').toggleClass('list'); return false;"">
                    <img src="{{ MEDIA_URL }}img/gallery-view.jpg" width="20" height="20" title="{% trans 'Switch to Gallery View' %}" />
                </a>
            </div>
        </div>
        
        <div id="gallery-results" name="mode-gallery">
            {% for product in result_list.object_list %}
            <div class="grid_3">
                <div class="item_box">
                    <a href="{% url market_buy_product_redirect product.product_id %}" target="_blank">
                    {% with product.child.image.image.url_100x100 as image_url %}
                    {% if image_url %}
                    <img class="item" src="{{ image_url }}" title="{{ product.description|striptags }}"/>
                    {% else %}
                    <img class="item" src="{{ MEDIA_URL }}img/no-photo-medium.jpg" title="{{ product.description|striptags }}"/>
                    {% endif %}
                    {% endwith %}
                    <div>{{ product.title|truncatewords:5 }}</div>
                    <div>{{ product.category.name }}</div>
                    <div>{{ product.price|format_price:product.shop_currency }}</div>
                    </a>
                </div>
            </div>
            {% endfor %}
        </div>

        <div id="list-results" name="mode-list">
            {% for product in result_list.object_list %}
            <div class="grid_13">
                <hr></hr>
                <div class="grid_2">
                    <a href="{% url market_buy_product_redirect product.product_id %}" target="_blank"> 
                    {% with product.child.image.image.url_100x100 as image_url %}
                    {% if image_url %}
                    <img class="item" src="{{ image_url }}" height="55" width="55" title="{{ product.description|striptags }}"/>
                    {% else %}
                    <img class="item" src="{{ MEDIA_URL }}img/no-photo-medium.jpg" height="51" width="56" title="{{ product.description|striptags }}"/>
                    {% endif %}
                    {% endwith %}
                    </a>
                </div>
                <div class="grid_7">
                    {{ product.title }}<br></br>
                    <a href="http://{{ product.shop_default_dns }}" target="_blank">{{ product.shop_name }}</a>
                </div>
                <div class="grid_3">
                    {{ product.price|format_price:product.shop_currency }}
                </div>
            </div>
            {% endfor %}
        </div>

        <div class="clear"></div>
        <div class="pagination">
            {% with result_list as objects %}
                {% include 'advanced_paginator.html'%}
            {% endwith %}
        </div>
        <div class="clear"></div>
    </div>
{% endblock %}

marketplaces/templates/default/buy/categories.html
{% extends "default/base.html" %}
{% load i18n %}

{% block content %}
<div id="breadcrumbs" class="grid_18">
	<a href="{% url market_home %}">{% trans "Home" %}</a> &raquo; <a href="{% url market_buy %}">{% trans "Buy" %}</a> &raquo; {% trans "Categories" %}
</div>

<div class="grid_18 block_main_content margin_h">
<h3>{% trans "All Categories" %}</h3>

{% for category in marketplace.marketcategory_set.all %}
<div class="grid_18 alpha omega category_box margin_v">
	<h4><b><a href="{% url market_search_category category.slug %}">{{ category.name }}</a></b></h4>
	{% for subcategory in category.subcategories.all %}
	<div class="grid_3">
		<a href="{% url market_search_subcategory category.slug subcategory.slug %}">{{ subcategory.name }}</a>
	</div>
	{% endfor %}
</div>
<hr></hr>
{% endfor %}

</div>

{% endblock %}

marketplaces/templates/default/buy/favorites.html
{% extends "default/base.html" %}
{% load i18n %}
{% load sell_tags %}

{% block content %}
<div id="breadcrumbs" class="grid_18">
	<a href="{% url market_home %}">{% trans "Home" %}</a> &raquo; <a href="{% url market_buy %}">{% trans "Buy" %}</a> &raquo; {% trans "Favorites" %}
</div>

<div class="grid_18 block_main_content">

<h3>{% trans "Rick's Picks" %}</h3>

{% for pick in picks %}
<div class="grid_3">
	
	<div class="item_box">
		<a href="{% url market_buy_product_redirect pick.product.id %}" target="_blank">
		<img class="item" src="{{ pick.product.child.image.image.url_100x100 }}" title="{{ pick.product.description|striptags }}"/>
		<div>{{ pick.product.title|truncatewords:5 }}</div>
		<div>{{ pick.product.category.name }}</div>
		<div>{{ pick.product.child.price|money_format:pick.product.shop }}</div>
		</a>
	</div>
	
</div>
{% endfor %}

<div class="clear"></div>

</div>

{% endblock %}

marketplaces/templates/default/buy/latest_items.html
{% extends "default/base.html" %}
{% load i18n %}
{% load sell_tags %}


{% block content %}
<div id="breadcrumbs" class="grid_18">
	<a href="{% url market_home %}">{% trans "Home" %}</a> &raquo; <a href="{% url market_buy %}">{% trans "Buy" %}</a> &raquo; {% trans "Latest Items" %}
</div>

<div class="grid_18 block_main_content">

<h3>{% trans "Latest Items" %}</h3>
<p>Find the Coin you've always looked for with our marketplace of dealers. Post Your Wish List For all the dealers to see.</p>

{% for product in latest_items %}
<div class="grid_18">	
	<div class="grid_4">
		<a href="{% url market_buy_product_redirect product.id %}" target="_blank">
		{% if product.child.image %}
	 	<img class="item" src="{{ product.child.image.image.url_100x100 }}" title="{{ product.description|striptags }}"/>
	 	{% else %}
	 	<img class="item" src="{{ MEDIA_URL }}img/no-photo-medium.jpg" title="{{ product.description|striptags }}"/>
	 	{% endif %}
		<div>{{ product.title|truncatewords:5 }}</div>
		<div>{{ product.category.name }}</div>
		<div>{{ product.child.price|money_format:product.shop }}</div>
		</a>
	</div>
	<div class="grid_10">
		<p>{% trans "More Items from" %} {{ product.shop }}</p>
		{% for other_product in product.shop.last_posted_products %}
		<div class="grid_1">
			<a href="{% url market_buy_product_redirect other_product.id %}" target="_blank">
			{% if other_product.child.image %}
			<img src="{{ other_product.child.image.image.url_100x100 }}" height="42" width="42" title="{{ other_product.description|striptags }}"/></img>
			{% else %}
			<img src="{{ MEDIA_URL }}img/no-photo-small.jpg" height="42" width="42" title="{{ other_product.description|striptags }}"/></img>
			{% endif %}
			</a>
		</div>
		{% endfor%}
	</div>
</div>
<div class="clear"></div>
{% endfor %}

</div>

{% endblock %}

marketplaces/templates/default/buy/wish_list.html
{% extends "default/base.html" %}
{% load i18n %}

{% block header %}

{% endblock %}

{% block content %}

<script type="text/javascript">
	$(document).ready(function() {
 
		$("#dialog_form").dialog({
			autoOpen: false,
			height: 520,
			width: 460,
			modal: true,
			position: 'center',
			resizable: false,
			draggable: false,
			overlay: {opacity: 0.9, background: "black"},
		});	
				
		$('#create_item').click(function() {
					$('#dialog_form').dialog('open');
		});
				
		$("#id_category").change(function () {
			categories= new Array()
		    $("#id_category option:selected").each(function () {
		    	categories.push($(this).val())
		    });
	    	$("#id_subcategory").empty();
		    if (categories.length > 0){
			      $.post("{% url ajax_get_subcategories %}", { 'categories': categories }, function(data){
				      $("#id_subcategory").append(data);
			      });
      		}
	    })
	    .trigger('change');
	});
</script>

<div id="breadcrumbs" class="grid_18">
	<a href="{% url market_home %}">{% trans "Home" %}</a> &raquo; <a href="{% url market_buy %}">{% trans "Buy" %}</a> &raquo; {% trans "Wish List" %}
</div>

<div class="grid_18 block_main_content maring_h">
<h3>{% trans "Wish List" %}</h3>
<p>Find the Coin you've always looked for with our marketplace of dealers. Post Your Wish List For all the dealers to see.</p>

{% if wish_list %}
<div class="grid_17">
	<div class="grid_5"><b>{% trans "Description" %}</b></div>
	<div class="grid_2"><b>{% trans "Posted By" %}</b></div>
	<div class="grid_2"><b>{% trans "Categoty" %}</b></div>
	<div class="grid_2"><b>{% trans "Subcategory" %}</b></div>
	<div class="grid_2"><b>{% trans "Ideal Price" %}</b></div>
	<div class="grid_3"><b>{% trans "Posted On" %}</b></div>
</div>
{% for item in wish_list %}
<div class="grid_17 {% cycle 'row1' 'row2' %} ">
	<div class="grid_5">{{ item.description.capitalize|safe }}</div>
	<div class="grid_2">
	{% if item.public %}
	{{ item.posted_by }}
	{% else %}
	*******
	{% endif %}
	</div>
	<div class="grid_2">{{ item.category.name }}</div>
	<div class="grid_2">{% if item.subcategory %}{{ item.subcategory.name }}{% else %} --- {% endif %}</div>
	<div class="grid_2">$ {{ item.ideal_price }}</div>
	<div class="grid_3">{{ item.posted_on|date:"d F Y H:i" }}</div>
</div>
<div class="clear"></div>
{% endfor %}
{% else %}
<div class="notice">{% trans "There is no wish list items posted yet..." %}</div>
{% endif %}

<div class="clear"></div>

<br/><br/><br/>
{% if user.is_authenticated %}
<div id="create_item" class="awesome small blue">{% trans "Post your item" %}</div>
{% else %}
<b>{% trans "You must be logged in to post in the wish list. " %} <a href="{% url market_buy_login %}?next={% url buy_wish_list %}">{% trans "Login Here" %}</a></>
{% endif %}

<div id="dialog_form">
	<form action="{% url post_wish_list_item %}" method="POST" name="form">
		{{ form.as_p }}
		<button type="submit" class="small awesome">{% trans 'Save Item' %}</button> 
	</form>
</div>
</div>
<div class="clear"></div>

{% endblock %}