marketplaces/urls.py
from django.conf import settings
from django.conf.urls.defaults import *
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    (r'^', include('market.urls')),
    (r'^buy/', include('market_buy.urls')),
    (r'^sell/', include('market_sell.urls')),
    (r'^community/', include('market_community.urls')),
    (r'^admin/reports/', include('reports.urls')),
    
    url(r'^admin/', include(admin.site.urls), name="admin"),
    url(r'^logout/$', 'auth.views.logout', name='logout'),
    url(r'^map/([\d]+)/$', 'bidding.views.bidding_map', name='bidding_map'),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
    )

marketplaces/apps/market/models.py
from auth.models import User

from django.contrib import admin
from django.db import models
from django.template.defaultfilters import slugify

class MarketPlace(models.Model):
    #length  
    name = models.CharField(max_length=92)
    slug = models.SlugField(max_length=92, unique=True)
    title = models.CharField(max_length=92)
    base_domain =  models.CharField(max_length=128, help_text="example: greatcoins.com", unique=True)
    contact_email = models.EmailField(help_text="This email will be shown in the contact us page", default="contact@yourstore.com")
    contact_phone = models.CharField(max_length=128, help_text="This phone will be shown in the contact us page", default="")
    charge_on_card_as = models.CharField(max_length=255, help_text="Collector City LLC", default="")
    template_prefix = models.SlugField(max_length=92, help_text="example: greatcoins", unique=True)
    
    def __unicode__(self):
        return self.name
    
    def privacy_policy(self):
        policies = self.privacypolicy_set.all()
        l = policies.count()
        if l > 0: return policies[l-1].text
   
class MarketCategory(models.Model):
    marketplace = models.ForeignKey(MarketPlace)
    name = models.CharField(max_length=60)
    slug = models.SlugField(max_length=60, unique=True)
    order = models.IntegerField(default=255)
    
    class Meta:
        ordering = ['order']

    def __unicode__(self):
        return "%s > %s" % (self.marketplace, self.name)
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(MarketCategory, self).save(*args, **kwargs)

class MarketSubCategory(models.Model):
    marketplace = models.ForeignKey(MarketPlace)
    name = models.CharField(max_length=60)
    slug = models.SlugField(max_length=60)
    parent = models.ForeignKey(MarketCategory, null=True, blank=True, related_name='subcategories')
    order = models.IntegerField(default=255)
    
    class Meta:
        unique_together = (('parent', 'slug'),)
        ordering = ['order']
    
    def __unicode__(self):
        return "%s > %s" % (self.parent, self.name)
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(MarketSubCategory, self).save(*args, **kwargs)

class MarketMailingListMember(models.Model):
    marketplace = models.ForeignKey(MarketPlace)
    email = models.EmailField()
    def __str__(self):
        return "%s > %s" % (self.marketplace, self.email)
    
class MarketPostCategory(models.Model):
    tag = models.CharField(max_length=80)
    slug = models.SlugField(max_length=80, unique=True)
    def __unicode__(self):
        return self.tag
        
    def save(self, *args, **kwargs):
        self.slug = slugify(self.tag)
        super(MarketPostCategory, self).save(*args, **kwargs)

class MarketBlogPost(models.Model):
    marketplace = models.ForeignKey(MarketPlace)
    title = models.CharField(max_length=60)
    body = models.TextField()
    posted_on = models.DateTimeField(auto_now_add=True)
    posted_by = models.ForeignKey(User)
    views = models.IntegerField(default=0, editable=False)
    allow_comments = models.BooleanField(default=False)
    slug = models.SlugField(max_length=80, unique=True, editable=False)
    #tags = models.
    
    class Admin:
        list_display   = ('title', 'posted_by', 'posted_on')
        list_filter    = ('publisher', 'publication_date')
        ordering       = ('-posted_on',)
        search_fields  = ('title', 'posted_on')

    def comments(self):
        comment_list = MarketPostComment.objects.filter(post=self).order_by("-commented_on")
        return comment_list
        
    def tags(self):
        return []
        
    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(MarketBlogPost, self).save(*args, **kwargs)
        
    def __unicode__(self):
        return "%s > %s" % (self.marketplace, self.title)
    
    def visited(self):
        self.views = self.views + 1
        self.save()
        
    def date(self):
        return self.posted_on.strftime("%B %d, %Y")

class MarketPostPick(models.Model):
    marketplace = models.ForeignKey(MarketPlace)
    post = models.ForeignKey(MarketBlogPost)
    order = models.IntegerField(default=5)


class MarketPostComment(models.Model):
    post = models.ForeignKey(MarketBlogPost)
    comment = models.TextField()
    commented_on = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User)

    def date(self):
        return self.commented_on.strftime("%B %d, %Y")

class PrivacyPolicy(models.Model):
    marketplace = models.ForeignKey(MarketPlace)
    text = models.TextField(default="")
    
    def __unicode__(self):
        return "%s > Privacy Policy" % self.marketplace
    
class TermsAndConditions(models.Model):
    marketplace = models.ForeignKey(MarketPlace)
    text = models.TextField(default="")
    
    def __unicode__(self):
        return "%s > Terms & Conditions" % self.marketplace

marketplaces/apps/market_sell/forms.py
import datetime
import logging

from django import forms
from django.conf import settings
from django.contrib.localflavor.us.forms import USStateSelect, USZipCodeField
from django.core.urlresolvers import reverse
from django.db import transaction
from django.utils.translation import ugettext as _

from auth.models import User
from payments.gateways.braintreegw import BraintreeGateway
from subscriptions.models import SubscriptionPlan
from shops.models import Shop, ShopBillingInfo
from users.models import Profile 


MONTHS = (
    ("01", "January"),
    ("02", "February"),
    ("03", "March"),
    ("04", "April"),
    ("05", "May"),
    ("06", "June"),
    ("07", "July"),
    ("08", "August"),
    ("09", "September"),
    ("10", "October"),
    ("11", "November"),
    ("12", "December"),
)

current_year = datetime.date.today().year
YEARS = ((current_year + i, current_year + i) for i in range(31))

if getattr(settings, 'BRAINTREE_PRODUCTION', True):
    INITIAL_CC = None
else:
    INITIAL_CC = "4111111111111111"


class ShopInfoForm(forms.Form):
    name_store = forms.RegexField(max_length=60, label =_("Your shop's name"), regex=r'^[\s\w+-]+$',
            error_messages = {'invalid': _("This value may contain only letters, numbers and - character.")})
    shop_name = forms.CharField(max_length=60, label =_("Your shop's web address"), help_text=".greatcoins.com")
    street = forms.CharField(max_length=100)
    city = forms.CharField(max_length=100)
    state = forms.CharField(widget=USStateSelect)
    zip = USZipCodeField()
    promotional_code = forms.CharField(max_length=100, required=False)
    
    def clean_shop_name(self):
        shop_name = self.cleaned_data["shop_name"]
        try:
            Shop.objects.get(name=shop_name)
        except Shop.DoesNotExist:
            return shop_name
        raise forms.ValidationError(_("A shop with that name already exists."))

    

class ShopBillingForm(forms.Form):
    
    #Billing Address
    billing_street = forms.CharField(max_length=100, required=True)
    billing_city = forms.CharField(max_length=100, required=True)
    billing_state = forms.CharField(widget=USStateSelect, required=True)
    billing_zip = USZipCodeField(required=True)
    
    #Billing information
    cc_number = forms.CharField(max_length=60, label =_("Credit Card Number"), initial=INITIAL_CC)
    cc_expiration_month = forms.ChoiceField(choices=MONTHS)
    cc_expiration_year = forms.ChoiceField(choices=YEARS)
    card_security_number = forms.CharField(max_length=4, label =_("Card Security Number"), required=True)

    terms = forms.BooleanField(required=False)
    
    def clean_terms(self):
        terms = self.cleaned_data["terms"]
        if terms:
            return terms
        else:
            raise forms.ValidationError(_("You must agree to the terms and conditions before you can create your account."))
    
    def clean(self):
        init_user = self.initial['user']
        cleaned_data = self.cleaned_data
        
#        try:
#            a = self.initial.get("result")
#            logging.critical(a)
#            return cleaned_data 
#        except Exception:
#            pass
#        
#        logging.critical("Trying to validate credit cards")
        
        if cleaned_data.has_key('cc_expiration_year') and cleaned_data.has_key('cc_expiration_month'):
            date_str =  "%s-%s" % (cleaned_data['cc_expiration_year'], cleaned_data['cc_expiration_month'])
            card_expire = datetime.datetime.strptime(date_str,  "%Y-%m")
        
            if card_expire < datetime.datetime.now():
                msg = u"Card expired."
                self._errors["cc_expiration_year"] = self.error_class([msg])
                self._errors["cc_expiration_month"] = self.error_class([msg])
    
                # These fields are no longer valid. Remove them from the
                # cleaned data.
                del cleaned_data["cc_expiration_year"]
                del cleaned_data["cc_expiration_month"]
        
        bt_gw = BraintreeGateway(settings.MERCHANT_ID, settings.PUBLIC_KEY, settings.PRIVATE_KEY)
        
        first_name = init_user.first_name
        last_name = init_user.first_name
        email = init_user.email
        cc_number = cleaned_data.get("cc_number", None)
        if cc_number is None: self._errors["cc_number"] = self.error_class(["This field is required!"])
        
        month = cleaned_data.get("cc_expiration_month", None)
        year = cleaned_data.get("cc_expiration_year", None)
        
        if month is None or year is None:
            raise forms.ValidationError(_("Expiration date invalid format."))
                
        cc_expiration_date = "%s/%s" % (month, year)
        cc_security_number = cleaned_data.get("card_security_number", None)
        if cc_security_number is None: self._errors["card_security_number"] = self.error_class(["This field is required!"])
        
        street = cleaned_data.get("billing_street", None)
        if street is None: self._errors["billing_street"] = self.error_class(["This field is required!"])
        city = cleaned_data.get("billing_city", None)
        if city is None: self._errors["billing_city"] = self.error_class(["This field is required!"])
        state = cleaned_data.get("billing_state", None)
        if state is None: self._errors["billing_state"] = self.error_class(["This field is required!"])
        zip = cleaned_data.get("billing_zip", None)
        if zip is None: forms.ValidationError(_(""))
                
        shop_name = "thisisafake.shop.com"
        shop_id = "-1"
        
        result = bt_gw.create_customer(first_name, last_name, email, cc_number, cc_expiration_date, cc_security_number, street, city, state, zip, shop_name, shop_id)
        if result.is_success:
            self.result = result
            self.initial["result"] = result
        else:
            raise forms.ValidationError(_(result.message))
        
        return  cleaned_data

class ShopPlanForm(forms.Form):
    #Plan ID
    plan_id = forms.ModelChoiceField(queryset=SubscriptionPlan.objects.filter(active=True), empty_label=None)
        


from django.contrib.formtools.wizard import FormWizard
from django.http import HttpResponseRedirect
from django.shortcuts import render_to_response

class ShopSignUpWizard(FormWizard):

    def process_step(self, request, form, step):
        if step == 0:
            from subscriptions.models import SubscriptionPlan
            
            promotional_code = request.POST.get("0-promotional_code", None)
            
            if promotional_code != u'' and promotional_code is not None:
                plans = SubscriptionPlan.objects.filter(active=True).filter(secret_code=promotional_code)
            else:
                plans = SubscriptionPlan.objects.filter(active=True).filter(visible=True).order_by('-price')
            self.extra_context = {'plans': plans, 'promotional_code': promotional_code}
    
    
    def parse_params(self, request, *args, **kwargs):
        current_step = self.determine_step(request, *args, **kwargs)
        if request.method == 'POST' and current_step == 2:
            self.initial[2] = {'user' : request.user }

    def get_template(self, step):
        return 'default/sell/signup_wizard_%s.html' % step
    
    @transaction.commit_on_success
    def done(self, request, form_list):
        user = request.user
        
        cleaned_data = {}
        [cleaned_data.update(form.cleaned_data) for form in form_list]
        
        plan_id = cleaned_data['plan_id'].plan_id
        
        #Update address
        profile = user.get_profile()
        profile.street_address = cleaned_data['street']
        profile.city = cleaned_data['city']
        profile.state = cleaned_data['state']
        profile.zip = cleaned_data['zip']
        profile.country = 'United States'
        profile.save()
        
        billing_street = cleaned_data['billing_street'].encode('ascii', 'ignore')
        billing_city = cleaned_data['billing_city'].encode('ascii', 'ignore')
        billing_state = cleaned_data['billing_state'].encode('ascii', 'ignore')
        billing_zip = cleaned_data['billing_zip'].encode('ascii', 'ignore')
        
        date_str =  "%s-%s" % (cleaned_data['cc_expiration_year'], cleaned_data['cc_expiration_month'])
        card_expire = datetime.datetime.strptime(date_str,  "%Y-%m")
        
        
        """ Create shop """
        shop = Shop.objects.create(marketplace=request.marketplace,
                                   name=cleaned_data['shop_name'].lower(), 
                                   admin=user,
                                   name_store=cleaned_data['name_store'])
        
        """ Braintree subscription """
        #Create a new Customer with Financial data in braintree
        bt_gw = BraintreeGateway(settings.MERCHANT_ID, settings.PUBLIC_KEY, settings.PRIVATE_KEY)
        
        result = (form_list[2]).result

        if result.is_success:
            customer_id = result.customer.id
            update = bt_gw.update_customer_shopname(customer_id, shop.id, shop.default_dns)
            
            if update.is_success:
                token = result.customer.credit_cards[0].token    
            else:
                transaction.rollback()
                request.flash['message'] = unicode(_("%s" % update.message))
                request.flash['severity'] = "error"
                return HttpResponseRedirect(reverse('market_sell_signup'))    
            
        else:
            transaction.rollback()
            logging.error(result.errors.errors.data)
            logging.error(result.message)
            request.flash['message'] = unicode(_("%s" % result.message))
            request.flash['severity'] = "error"
            return HttpResponseRedirect(reverse('market_sell_signup'))
        
        #Create a Subscription in braintree linked to the customer created before

marketplaces/templates/default/sell/privacy.html
{% extends "default/base.html" %}
{% load i18n %}

{% block content %}
<div id="breadcrumbs" class="grid_18">
	<a href="{% url market_home %}">{% trans "Home" %}</a> &raquo; <a href="{% url market_sell %}">{% trans "Privacy Policy" %}</a>
</div>

{% block filter_content %}
<div class="grid_3 alpha omega block_filter">
	<h4>{% trans "Dealer Resources" %}</h4>
	<ul class="sell_dealer_resources">
		<li><a class="sell_dealer_resources" href="/">{% trans "Create an account" %}</a></li>
		<li><a class="sell_dealer_resources" href="/">{% trans "Naming my Store" %}</a></li>
		<li><a class="sell_dealer_resources" href="/">{% trans "Do'es and Don't" %}</a></li>
		<li><a class="sell_dealer_resources" href="/">{% trans "Fees/Pricing" %}</a></li>
		<li><a class="sell_dealer_resources" href="/">{% trans "Selling FAQ" %}</a></li>
		<li><a class="sell_dealer_resources" href="{% url market_privacy_policy %}">{% trans "Privacy Policy" %}</a></li>
	</ul>
</div>
{% endblock %}

<div class="grid_14 alpha omega block_main_content margin_h">
	
<h1>{% trans "PRIVACY POLICY" %}</h1>
<br/>
<p>
{{ marketplace.privacy_policy|safe }}
</p>

</div>

{% endblock %}

marketplaces/templates/default/sell/signup.html
{% extends "default/base.html" %}

{% load i18n %}

{% block content %}
<div class="grid_14 prefix_2">
		<form name="form" method="post" action="." class="big_form">
			<fieldset class="register">
			{% if form.name_store.errors %}<div class="error">{{ form.name_store.errors|join:", " }}</div>{% endif %}
			<h4>{{ form.name_store.label }}</h4>
			{{ form.name_store }}
			<br/><br/>
			
			{% if form.shop_name.errors %}<div class="error">{{ form.shop_name.errors|join:", " }}</div>{% endif %}
			<h4>{{ form.shop_name.label }}</h4>
			<label>http://{{ form.shop_name }}.{{ marketplace.base_domain }}</label>
			<br/><br/><br/><br/>
			
			<h4>{% trans "Create your administration account" %}</h4>
			<br/>

			{% if form.first_name.errors %}<div class="error">{{ form.first_name.errors|join:", " }}</div>{% endif %}
			<h5>{{ form.first_name.label }}</h5>
			{{ form.first_name }}

			{% if form.last_name.errors %}<div class="error">{{ form.last_name.errors|join:", " }}</div>{% endif %}
			<h5>{{ form.last_name.label }}</h5>
			{{ form.last_name }}

			{% if form.username.errors %}<div class="error">{{ form.username.errors|join:", " }}</div>{% endif %}
			<h5>{{ form.username.label }}</h5>
			{{ form.username }}
			
			{% if form.email.errors %}<div class="error">{{ form.email.errors|join:", " }}</div>{% endif %}
			<h5>{{ form.email.label }}</h5>
			{{ form.email }}

			{% if form.password1.errors %}<div class="error">{{ form.password1.errors|join:", " }}</div>{% endif %}
			<h5>{{ form.password1.label }}</h5>
			{{ form.password1 }}

			{% if form.password2.errors %}<div class="error">{{ form.password2.errors|join:", " }}</div>{% endif %}
			<h5>{{ form.password2.label }}</h5>
			{{ form.password2 }}
			
			<br/><br/>
			
			<h4>{% trans "Choose your plan" %}</h4>
			<br/>
			{% if form.plan_id.errors %}<div class="error">{{ form.plan_id.errors|join:", " }}</div>{% endif %}
			{{ form.plan_id }}

			<br/><br/>
			
			<h4>{% trans "Your Billing Address" %}</h4>
			<br/>
			{% if form.street.errors %}<div class="error">{{ form.street.errors|join:", " }}</div>{% endif %}
			<h5>{{ form.street.label }}</h5>
			{{ form.street }}
			
			{% if form.city.errors %}<div class="error">{{ form.city.errors|join:", " }}</div>{% endif %}
			<h5>{{ form.city.label }}</h5>
			{{ form.city }}
			
			{% if form.zip.errors %}<div class="error">{{ form.zip.errors|join:", " }}</div>{% endif %}
			<h5>{{ form.zip.label }}</h5>
			{{ form.zip }}
			
			{% if form.state.errors %}<div class="error">{{ form.state.errors|join:", " }}</div>{% endif %}
			<h5>{{ form.state.label }}</h5>
			{{ form.state }}
			
			{% if form.country.errors %}<div class="error">{{ form.country.errors|join:", " }}</div>{% endif %}
			<h5>{{ form.country.label }}</h5>
			{{ form.country }}
			
			<br/><br/>
			
			<h4>{% trans "Your billing information" %}</h4>
			<br/>
			{% if form.cc_number.errors %}<div class="error">{{ form.cc_number.errors|join:", " }}</div>{% endif %}
			<h5>{{ form.cc_number.label }}</h5>
			{{ form.cc_number }}
			
			<h5>{% trans "Expiration Date" %}</h5>
			{% if form.cc_expiration_month.errors %}<div class="error">{{ form.cc_expiration_month.errors|join:", " }}</div>{% endif %}
			{{ form.cc_expiration_month }}
			{{ form.cc_expiration_year }}
			
			<br/><br/>

			{% if form.card_security_number.errors %}<div class="error">{{ form.card_security_number.errors|join:", " }}</div>{% endif %}
			<h5>{{ form.card_security_number.label }}</h5>
			{{ form.card_security_number }}
			
			<a href="https://www.braintreegateway.com/merchants/{{ merchant_id }}/verified" target="_blank">
				<img src="https://braintree-badges.s3.amazonaws.com/01.png" border="0"/>
			</a>
			
			<br/><br/><br/>
			<h4>{% trans "Your Address" %}</h4>
			<label><input type="checkbox" id="id_same_as_billing" {% if address_as_billing %}checked="checked"{% endif %} name="address_same_as_billing" value="1"/> Same as billing address</label>
			<div id="shop_address_form" {% if address_as_billing %}style="display: none;"{% endif %}>
			<br/><br/>
			{% if form_address.street.errors %}<div class="error">{{ form_address.street.errors|join:", " }}</div>{% endif %}
			<h5>{{ form_address.street.label }}</h5>
			{{ form_address.street }}
			
			{% if form_address.city.errors %}<div class="error">{{ form_address.city.errors|join:", " }}</div>{% endif %}
			<h5>{{ form_address.city.label }}</h5>
			{{ form_address.city }}
			
			{% if form_address.zip.errors %}<div class="error">{{ form_address.zip.errors|join:", " }}</div>{% endif %}
			<h5>{{ form_address.zip.label }}</h5>
			{{ form_address.zip }}
			
			{% if form_address.state.errors %}<div class="error">{{ form_address.state.errors|join:", " }}</div>{% endif %}
			<h5>{{ form_address.state.label }}</h5>
			{{ form_address.state }}
			
			{% if form_address.country.errors %}<div class="error">{{ form_address.country.errors|join:", " }}</div>{% endif %}
			<h5>{{ form_address.country.label }}</h5>
			{{ form_address.country }}
			</div>
			
			<script>
			$(function() {
				$('#id_same_as_billing').click(function() { 
					$("#shop_address_form").toggle(!this.checked); 
				});
			})
			</script>
			
			<br/><br/>
			
			<h4>{% trans "Terms and conditions" %}</h4>

			{% if form.terms.errors %}<div class="error">{{ form.terms.errors|join:", " }}</div>{% endif %}
			<label>{{ form.terms }} {% trans "I have read and agree to the" %} <a href="" class="blue">{% trans "Terms & Conditions" %}</a></label>
			<br/><br/><br/><br/>
			<div class="buttonHolder">
				<br/>
				<button type="submit" class="button_primary">{% trans "Create Store" %}</button>
		       	<input type="hidden" name="next" value="{{ next|escape }}" />
		    </div>
			</fieldset>
		</form>
		<script type="text/javascript"> 
	$("#id_name_store").keyup(function(e){
	    var name = $(this).val();
	       $("#id_shop_name").val(name.toLowerCase().replace(/[^a-z0-9-]/ig, ''));
	       $("#id_username").val(name.toLowerCase().replace(/[^a-z0-9-]/ig, ''));
	}); 
	</script> 
</div>
<div class="clear"></div>
{% endblock %}

marketplaces/templates/default/sell/signup_wizard_0.html
{% extends "default/sell/signup_wizard_base.html" %}

{% load i18n %}

{% block step %}
<form name="form" method="post" action="." class="wizard">
	
	{% csrf_token %}
	{% for field in form %}
	{% if field.errors %}<div class="error">{{ field.errors|join:", " }}</div>{% endif %}
	<h4>{{ field.label }}</h4>
	{{ field }} {{ field.help_text }}
	<br/><br/>
	{% endfor %}
	
	<input type="hidden" name="{{ step_field }}" value="{{ step0 }}" />
	{{ previous_fields|safe }}
	<div class="buttonHolder">
		<br/>
		<button type="submit" class="button_next">{% trans "Next" %}</button>
       	<input type="hidden" name="next" value="{{ next|escape }}" />
    </div>
	
</form>

<style>
#id_0-shop_name {
	width: 150px;
}
</style>

<script type="text/javascript"> 
$("#id_0-name_store").keyup(function(e){
    var name = $(this).val();
   	$("#id_0-shop_name").val(name.toLowerCase().replace(/[^a-z0-9-]/ig, ''));
}); 

$("#id_0-shop_name").change(function(){
	var name = $(this).val();
	$(this).val(name.toLowerCase().replace(/[^a-z0-9-]/ig, ''));
});

</script> 
{% endblock %}

marketplaces/templates/default/sell/signup_wizard_2.html
{% extends "default/sell/signup_wizard_base.html" %}

{% load i18n %}

{% block step %}
<script type="text/javascript" src="{{ MEDIA_URL}}js/tiny_mce/tiny_mce.js"></script>
<script type="text/javascript">
tinyMCE.init({
	mode : "textareas",	
	theme : "advanced",
	readonly : true ,
});
</script>

<form name="form" method="post" action="." class="wizard">
	{% if form.non_field_errors %} Error : <div class="error">{{ form.non_field_errors }}</div>{% endif %}

	{% csrf_token %}
	{% for field in form %}
	{% if field.errors %}<div class="error">{{ field.errors|join:", " }}</div>{% endif %}
	<h4>{{ field.label.title }}</h4>
	{% if field.label.title == "Terms" %}
	<textarea rows="20" cols="80">
	{{ marketplace.termsandconditions_set.all.0.text }}
	</textarea>
	<div class="grid_2">{{ field }} I Agree</div>
	{% else %}
	{{ field }} {{ field.help_text }}
	{% endif %}
	<br/><br/>
	{% endfor %}
	
	<input type="hidden" name="{{ step_field }}" value="{{ step0 }}" />
	{{ previous_fields|safe }}

	<div class="buttonHolder">
		<br/>
		<button type="submit" class="button_next">{% trans "Next" %}</button>
       	<input type="hidden" name="next" value="{{ next|escape }}" />
    </div>
	</fieldset>
</form> 
{% endblock %}

marketplaces/templates/default/sell/signup_wizard_base.html
{% extends "default/base.html" %}
{% load i18n %}

{% block content %}
<div id="breadcrumbs" class="grid_18">
	<a href="{% url market_home %}">{% trans "Home" %}</a> &raquo; <a href="{% url market_sell %}">{% trans "Sell" %}</a> &raquo; {% trans "Sign Up" %}
</div>

<div class="grid_14 block_main_content">
<div class="step_guide">
	<h3>{% trans "Sign Up for Your Store" %}</h3>
	<span {% if step == 1 %}class="current"{% endif %}>1. {% trans "Store Info" %}</span>
	<span {% if step == 2 %}class="current"{% endif %}>2. {% trans "Choose Your Plan" %}</span>
	<span {% if step == 3 %}class="current"{% endif %}>3. {% trans "Billing" %}</span>
	<span>4.  {% trans "Welcome" %}</span>
</div>

<div class="clear"></div>

{% block step %}{% endblock %} 
</div>

<div class="grid_3 block_filter">
	Already A Seller? <a href="{% url market_buy_login %}">{% trans "Sign In here" %}</a>
	<br/><br/>
	<h4>{% trans "Privacy Policy" %}</h4>
	<p>{% trans "We take your privacy seriouly" %}</p>
	<ul>
		<li><a href="{% url market_privacy_policy %}">{% trans "Privacy Policy" %}</a></li>
	</ul>
</div>

<div class="clear"></div>

{% endblock %}